//! Self-contained HTML report: commit timeline, semantic diff, and integrity
//! status on a single static page (inline CSS, no JavaScript, no external
//! assets). Like the CLI, this is just another front-end over the engine's
//! data — it renders [`Commit`]s, a [`SnapshotDiff`] and a [`VerifyReport`]
//! that the caller has already gathered.

use std::fmt::Write as _;

use dbsnap_core::{format_unix_utc, Commit, DbHash};
use dbsnap_diff::SnapshotDiff;
use dbsnap_integrity::VerifyReport;
use serde_json::Value;

/// The diff section of a report: a range and its computed difference.
pub struct DiffView<'a> {
    pub old_ref: &'a str,
    pub new_ref: &'a str,
    pub diff: &'a SnapshotDiff,
}

/// Everything needed to render a report.
pub struct ReportInput<'a> {
    /// Pre-formatted "generated at" string.
    pub generated_at: &'a str,
    /// Current HEAD, if any.
    pub head: Option<&'a DbHash>,
    /// Commit history, newest first.
    pub history: &'a [(DbHash, Commit)],
    /// Optional diff section.
    pub diff: Option<DiffView<'a>>,
    /// Integrity verification result.
    pub verify: &'a VerifyReport,
}

/// Render a complete, self-contained HTML document.
pub fn render(input: &ReportInput) -> String {
    let mut h = String::with_capacity(8 * 1024);
    h.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n");
    h.push_str("<meta charset=\"utf-8\">\n");
    h.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    h.push_str("<title>dbsnap report</title>\n<style>\n");
    h.push_str(STYLE);
    h.push_str("\n</style>\n</head>\n<body>\n");

    render_header(&mut h, input);
    render_integrity(&mut h, input.verify);
    if let Some(diff) = &input.diff {
        render_diff(&mut h, diff);
    }
    render_timeline(&mut h, input);

    h.push_str("<footer>Generated by dbsnap — deterministic database snapshots, diffs and integrity verification.</footer>\n");
    h.push_str("</body>\n</html>\n");
    h
}

fn render_header(h: &mut String, input: &ReportInput) {
    h.push_str("<header>\n<h1>dbsnap report</h1>\n<div class=\"meta\">");
    let _ = write!(h, "Generated {}", esc(input.generated_at));
    if let Some(head) = input.head {
        let _ = write!(h, " · HEAD <code>{}</code>", esc(&head.short()));
    }
    let _ = write!(h, " · {} commit(s)", input.history.len());
    h.push_str("</div>\n</header>\n");
}

fn render_integrity(h: &mut String, report: &VerifyReport) {
    let class = if report.ok() { "card ok" } else { "card bad" };
    let _ = write!(h, "<section class=\"{class}\">\n<h2>Integrity</h2>\n");
    let _ = writeln!(
        h,
        "<p class=\"counts\">Checked {} commit(s), {} table(s), {} row(s).</p>",
        report.commits_checked, report.tables_checked, report.rows_checked
    );
    if report.ok() {
        h.push_str("<p class=\"verdict ok\">✓ Hash chain intact — no tampering detected.</p>\n");
    } else {
        let _ = write!(
            h,
            "<p class=\"verdict bad\">✗ {} integrity violation(s) detected:</p>\n<ul class=\"violations\">\n",
            report.violations.len()
        );
        for v in &report.violations {
            let _ = writeln!(
                h,
                "<li><span class=\"vkind\">{}</span> {}</li>",
                esc(&v.kind),
                esc(&v.detail)
            );
        }
        h.push_str("</ul>\n");
    }
    h.push_str("</section>\n");
}

fn render_diff(h: &mut String, view: &DiffView) {
    let diff = view.diff;
    let _ = write!(
        h,
        "<section class=\"card\">\n<h2>Changes <code>{}</code> → <code>{}</code></h2>\n",
        esc(view.old_ref),
        esc(view.new_ref)
    );

    if diff.is_empty() {
        h.push_str("<p class=\"empty\">No changes between these commits.</p>\n</section>\n");
        return;
    }

    for t in &diff.added_tables {
        let _ = writeln!(h, "<p class=\"badge add\">+ table {}</p>", esc(t));
    }
    for t in &diff.removed_tables {
        let _ = writeln!(h, "<p class=\"badge del\">− table {}</p>", esc(t));
    }

    for t in &diff.tables {
        let _ = write!(
            h,
            "<div class=\"table\">\n<h3>{}</h3>\n<div class=\"badges\">",
            esc(&t.table)
        );
        if !t.inserted.is_empty() {
            let _ = write!(
                h,
                "<span class=\"badge add\">+{} inserted</span>",
                t.inserted.len()
            );
        }
        if !t.updated.is_empty() {
            let _ = write!(
                h,
                "<span class=\"badge upd\">~{} updated</span>",
                t.updated.len()
            );
        }
        if !t.deleted.is_empty() {
            let _ = write!(
                h,
                "<span class=\"badge del\">−{} deleted</span>",
                t.deleted.len()
            );
        }
        h.push_str("</div>\n");

        if !t.updated.is_empty() {
            let _ = write!(
                h,
                "<details>\n<summary>{} updated row(s)</summary>\n<table class=\"changes\">\n",
                t.updated.len()
            );
            h.push_str("<thead><tr><th>pk</th><th>column</th><th>old</th><th>new</th></tr></thead>\n<tbody>\n");
            for row in &t.updated {
                let span = row.columns.len().max(1);
                for (i, c) in row.columns.iter().enumerate() {
                    h.push_str("<tr>");
                    if i == 0 {
                        let _ = write!(
                            h,
                            "<td class=\"pk\" rowspan=\"{span}\"><code>{}</code></td>",
                            esc(&row.pk)
                        );
                    }
                    let _ = write!(
                        h,
                        "<td class=\"col\">{}</td><td class=\"old\">{}</td><td class=\"new\">{}</td>",
                        esc(&c.column),
                        val(&c.old),
                        val(&c.new)
                    );
                    h.push_str("</tr>\n");
                }
            }
            h.push_str("</tbody>\n</table>\n</details>\n");
        }

        render_pk_list(h, "inserted", "add", &t.inserted);
        render_pk_list(h, "deleted", "del", &t.deleted);

        h.push_str("</div>\n");
    }
    h.push_str("</section>\n");
}

fn render_pk_list(h: &mut String, label: &str, class: &str, pks: &[String]) {
    if pks.is_empty() {
        return;
    }
    let _ = write!(
        h,
        "<details>\n<summary>{} {} primary key(s)</summary>\n<ul class=\"pks {}\">\n",
        pks.len(),
        label,
        class
    );
    for pk in pks {
        let _ = writeln!(h, "<li><code>{}</code></li>", esc(pk));
    }
    h.push_str("</ul>\n</details>\n");
}

fn render_timeline(h: &mut String, input: &ReportInput) {
    h.push_str("<section class=\"card\">\n<h2>Timeline</h2>\n");
    if input.history.is_empty() {
        h.push_str("<p class=\"empty\">No commits yet.</p>\n</section>\n");
        return;
    }
    h.push_str("<ol class=\"timeline\">\n");
    for (i, (hash, commit)) in input.history.iter().enumerate() {
        let is_head = i == 0;
        let _ = write!(
            h,
            "<li>\n<div class=\"commit-head\"><code class=\"hash\">{}</code>",
            esc(&hash.short())
        );
        if is_head {
            h.push_str(" <span class=\"tag\">HEAD</span>");
        }
        h.push_str("</div>\n");
        let _ = writeln!(h, "<div class=\"msg\">{}</div>", esc(commit.summary()));
        let _ = writeln!(
            h,
            "<div class=\"sub\">{} · {} · tree <code>{}</code></div>",
            esc(&commit.author),
            esc(&format_unix_utc(commit.timestamp)),
            esc(&commit.tree.short())
        );
        h.push_str("</li>\n");
    }
    h.push_str("</ol>\n</section>\n");
}

/// Compact, HTML-escaped rendering of a JSON value for the diff table.
fn val(v: &Value) -> String {
    let s = match v {
        Value::Null => "∅".to_string(),
        Value::String(s) => s.clone(),
        other => other.to_string(),
    };
    let truncated = if s.chars().count() > 120 {
        let mut t: String = s.chars().take(119).collect();
        t.push('…');
        t
    } else {
        s
    };
    format!("<code>{}</code>", esc(&truncated))
}

/// HTML-escape text content.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const STYLE: &str = r#":root {
  --bg: #f6f7f9; --card: #fff; --ink: #1c2128; --muted: #6b7280; --line: #e5e7eb;
  --add: #1a7f37; --addbg: #e9f6ec; --del: #cf222e; --delbg: #fbe9ea;
  --upd: #9a6700; --updbg: #fdf3d8; --ok: #1a7f37; --bad: #cf222e;
}
* { box-sizing: border-box; }
body { margin: 0; padding: 0 0 4rem; background: var(--bg); color: var(--ink);
  font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
header { background: #0d1117; color: #fff; padding: 1.5rem 2rem; }
header h1 { margin: 0; font-size: 1.4rem; }
header .meta { color: #9da7b3; margin-top: .35rem; font-size: .9rem; }
header code { color: #d1d5db; }
section.card { background: var(--card); margin: 1.25rem 2rem; padding: 1.25rem 1.5rem;
  border: 1px solid var(--line); border-radius: 10px; }
section.card.ok { border-left: 4px solid var(--ok); }
section.card.bad { border-left: 4px solid var(--bad); }
h2 { margin: 0 0 .75rem; font-size: 1.1rem; }
h3 { margin: 1rem 0 .35rem; font-size: 1rem; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .88em;
  background: #f0f1f3; padding: .05rem .3rem; border-radius: 4px; }
.counts, .sub { color: var(--muted); font-size: .9rem; }
.verdict { font-weight: 600; }
.verdict.ok { color: var(--ok); }
.verdict.bad { color: var(--bad); }
.violations { margin: .25rem 0 0; }
.vkind { display: inline-block; background: var(--delbg); color: var(--del);
  border-radius: 4px; padding: 0 .35rem; font: .8rem ui-monospace, monospace; margin-right: .4rem; }
.badges { display: flex; gap: .5rem; flex-wrap: wrap; margin: .25rem 0 .5rem; }
.badge { display: inline-block; border-radius: 999px; padding: .1rem .6rem; font-size: .82rem; font-weight: 600; }
.badge.add { background: var(--addbg); color: var(--add); }
.badge.upd { background: var(--updbg); color: var(--upd); }
.badge.del { background: var(--delbg); color: var(--del); }
.table { border-top: 1px solid var(--line); padding-top: .5rem; margin-top: .5rem; }
.table:first-of-type { border-top: 0; }
details { margin: .4rem 0; }
summary { cursor: pointer; color: var(--muted); font-size: .9rem; }
table.changes { border-collapse: collapse; width: 100%; margin: .5rem 0; font-size: .9rem; }
table.changes th, table.changes td { border: 1px solid var(--line); padding: .3rem .5rem; text-align: left; vertical-align: top; }
table.changes th { background: #fafbfc; font-weight: 600; }
td.old code { background: var(--delbg); }
td.new code { background: var(--addbg); }
ul.pks { columns: 4; list-style: none; padding: 0; margin: .35rem 0; }
ul.pks li { font-size: .85rem; }
.empty { color: var(--muted); font-style: italic; }
ol.timeline { list-style: none; margin: 0; padding: 0; }
ol.timeline li { border-left: 2px solid var(--line); padding: .15rem 0 .9rem 1rem; position: relative; }
ol.timeline li::before { content: ""; position: absolute; left: -5px; top: .45rem;
  width: 8px; height: 8px; border-radius: 50%; background: var(--muted); }
ol.timeline li:first-child::before { background: var(--ok); }
.commit-head { display: flex; align-items: center; gap: .5rem; }
.hash { background: #eef1f4; }
.tag { background: var(--ok); color: #fff; border-radius: 4px; padding: 0 .4rem; font-size: .72rem; font-weight: 700; }
.msg { font-weight: 600; margin: .15rem 0; }
footer { color: var(--muted); text-align: center; font-size: .82rem; margin-top: 2rem; }"#;
